name: build-release

on:
  push:
    tags:
      - v*.*.*
      - v*.*.*-beta.*

jobs:
  
  build-pixinsight-script:
    runs-on: ubuntu-latest
    steps:
      - name: store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GraXpert.js
          path: ./src/scripts/GraXpert/GraXpert.js
          retention-days: 5

  release:
    runs-on: ubuntu-latest
    needs: [build-pixinsight-script]
    steps:
      - name: download pixinsight script
        uses: actions/download-artifact@v2
        with:
          name: GraXpert.js
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            GraXpert.js
